name: Build Installation Files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Tag Name on Release
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        if: github.event_name == 'release'

      - name: Extract Tag Name on Workflow Dispatch
        id: get-latest-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repository=${{ github.repository }}
          latest_release=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$repository/tags" | jq -r '.[0].name')
          echo "TAG_NAME=$latest_release" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Get Slicer Stable Revision and Version
        id: get_slicer_info
        run: |
          echo "SLICER_INFO=$(python -c '
          import requests
          from bs4 import BeautifulSoup
          url = "https://download.slicer.org"
          response = requests.get(url)
          soup = BeautifulSoup(response.text, "html.parser")
          link = soup.select_one("section div div div div div div table tbody tr td a")
          if link is not None:
              revision = link.text.split("\n")[2].strip().split(" ")[-1]
              version = link.text.split("\n")[1].strip().split(".")
              version = ".".join(version[:2])
              print(version, revision)
          else:
              print("unknown unknown")
          ')" >> $GITHUB_ENV
        shell: bash

      - name: Set Version and Revision as ENV Variables
        run: |
          echo "VERSION=$(echo ${{ env.SLICER_INFO }} | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "REVISION=$(echo ${{ env.SLICER_INFO }} | cut -d' ' -f2)" >> $GITHUB_ENV
          if [[ "${{ env.VERSION }}" == "unknown" ]]; then
            echo "Version is unknown"
            exit 1
          fi
        shell: bash

      - name: Get Extension Name
        id: ext_name
        run: |
          echo "EXT_NAME=$(echo ${GITHUB_REPOSITORY#*/} | sed 's/^Slicer//')" >> $GITHUB_ENV

      - name: Set Directory Paths as ENV Variables
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "MAIN_DIR_W=${{ env.REVISION }}-win-amd64-${{ env.EXT_NAME }}" >> $GITHUB_ENV
          echo "DIR1_W=${{ env.REVISION }}-win-amd64-${{ env.EXT_NAME }}/lib/Slicer-${{ env.VERSION }}/qt-scripted-modules/" >> $GITHUB_ENV
          echo "DIR2_W=${{ env.REVISION }}-win-amd64-${{ env.EXT_NAME }}/share/Slicer-${{ env.VERSION }}/" >> $GITHUB_ENV

          echo "MAIN_DIR_L=${{ env.REVISION }}-linux-amd64-${{ env.EXT_NAME }}" >> $GITHUB_ENV
          echo "DIR1_L=${{ env.REVISION }}-linux-amd64-${{ env.EXT_NAME }}/lib/Slicer-${{ env.VERSION }}/qt-scripted-modules/" >> $GITHUB_ENV
          echo "DIR2_L=${{ env.REVISION }}-linux-amd64-${{ env.EXT_NAME }}/share/Slicer-${{ env.VERSION }}/" >> $GITHUB_ENV

          echo "MAIN_DIR_M=${{ env.REVISION }}-macosx-amd64-${{ env.EXT_NAME }}" >> $GITHUB_ENV
          echo "DIR1_M=${{ env.REVISION }}-macosx-amd64-${{ env.EXT_NAME }}/Slicer.app/Contents/Extensions-${{ env.REVISION }}/${{ env.EXT_NAME }}/lib/Slicer-${{ env.VERSION }}/qt-scripted-modules/" >> $GITHUB_ENV
          echo "DIR2_M=${{ env.REVISION }}-macosx-amd64-${{ env.EXT_NAME }}/Slicer.app/Contents/Extensions-${{ env.REVISION }}/${{ env.EXT_NAME }}/share/Slicer-${{ env.VERSION }}/" >> $GITHUB_ENV

        shell: bash

      - name: Create Directory Structure
        run: |
          mkdir -p ${{ env.DIR1_W }}
          mkdir -p ${{ env.DIR2_W }}
          mkdir -p ${{ env.DIR1_L }}
          mkdir -p ${{ env.DIR2_L }}
          mkdir -p ${{ env.DIR1_M }}
          mkdir -p ${{ env.DIR2_M }}
        shell: bash

      - name: Copy Files
        run: |
          cp -R ${{ env.EXT_NAME }}/* ${{ env.DIR1_W }}
          rm ${{ env.DIR1_W }}/CMakeLists.txt
          cp ${{ env.EXT_NAME }}.s4ext ${{ env.DIR2_W }}

          cp -R ${{ env.EXT_NAME }}/* ${{ env.DIR1_L }}
          rm ${{ env.DIR1_L }}/CMakeLists.txt
          cp ${{ env.EXT_NAME }}.s4ext ${{ env.DIR2_L }}

          cp -R ${{ env.EXT_NAME }}/* ${{ env.DIR1_M }}
          rm ${{ env.DIR1_M }}/CMakeLists.txt
          cp ${{ env.EXT_NAME }}.s4ext ${{ env.DIR2_M }}
        shell: bash

      - name: Archive Files
        run: |
          zip -r ${{ env.MAIN_DIR_W }}-${{ env.DATE }}.zip ${{ env.MAIN_DIR_W }}
          tar -czvf ${{ env.MAIN_DIR_L }}-${{ env.DATE }}.tar.gz ${{ env.MAIN_DIR_L }}
          tar -czvf ${{ env.MAIN_DIR_M }}-${{ env.DATE }}.tar.gz ${{ env.MAIN_DIR_M }}

      - name: Upload Archive to Current Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.MAIN_DIR_W }}-${{ env.DATE }}.zip
            ${{ env.MAIN_DIR_L }}-${{ env.DATE }}.tar.gz
            ${{ env.MAIN_DIR_M }}-${{ env.DATE }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Archive to Latest Release
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $TAG_NAME ${{ env.MAIN_DIR_W }}-${{ env.DATE }}.zip --clobber
          gh release upload $TAG_NAME ${{ env.MAIN_DIR_L }}-${{ env.DATE }}.tar.gz --clobber
          gh release upload $TAG_NAME ${{ env.MAIN_DIR_M }}-${{ env.DATE }}.tar.gz --clobber
